config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new,  :destroy, :create]
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :session_token, :password_digest, presence: true
  validates_uniqueness_of :email

  after_initialize :ensure_session_token


  def self.find_by_credentials(email, password)
    found = User.find_by(email: email)
    if found
      return found if found.is_password?(password)
      nil
    end
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end


  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end # this will still get called regardlessly, because this is overwriting
  #active record's default methods


  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    User.find_by_session_token(session[:token])
    # fail
  end

  def logged_in?
    return true if current_user
    false
  end

  def log_in_user!(user)
    user.reset_session_token!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
              session_params[:email],
              session_params[:password]
            )
    if @user.nil?
      flash.now[:errors] = ["Invalid Username and Password Combo"]
      render :new
    else
      @user.reset_session_token!
      session[:token] = @user.session_token
      redirect_to user_url(@user.id)
    end
  end


  def destroy
    if current_user
      current_user.reset_session_token!
      session[:token] = nil
    end

    render :new
  end


  private
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save # jsut returns false, doesn't throw errors
      #login user
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

    # render :show
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_authentic.html.erb
<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_login.html.erb
<%if logged_in? %>
<p>
  Hai <%= current_user.email %>!
  <%= link_to "Logout", session_url, method: :delete %>
</p>
<p>
<% else %>
  <%= link_to "Login", new_session_url %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/login" %>
  <%= render "layouts/errors" %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action=" <%= users_url %>" method="post">

  <%= render "layouts/authentic" %>
  <h2>Please Create a Login</h2>
  <p>
    <label for="user[email]">Email: </label>
    <input type="text" name="user[email]" value="">
  </p>
  <label for="user[password]">Password: </label>
  <input type="text" name="user[password]" value="">
  <input type="submit" name="Create User" value="CREATE ME">
</form>

app/views/users/show.html.erb
<h1> Hello <%= @user.email%> !</h1>
<%= current_user.email unless current_user.nil?%>